## 카이제곱 검정
 두 범주형 변수가 서로 독립적인지 검정

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("datas2/성별에따른만족도.csv", encoding='euc-kr')
df.head()

   만족도  성별
0  불만족  남성
1   보통  여성
2  불만족  여성
3   보통  남성
4   만족  여성

In [5]:
#실제값 교차테이블 생성

cross_table = pd.crosstab(df['성별'], df['만족도'])
cross_table

만족도  만족  보통  불만족
성별
남성   50  40   10
여성   40  30   30

In [6]:
#실제값 numpy 배열로 만들기 

obs = cross_table.values
obs

array([[50, 40, 10],
       [40, 30, 30]])

#### 성별에 따른 만족도를 분석한다.
귀무가설(H₀): 성별과 구매 여부는 서로 관련이 없다. 즉, 독립이다.
대립가설(H₁): 성별과 구매 여부는 서로 관련이 있다. 즉, 독립이 아니다.

In [7]:
from scipy import stats
statistics, pvalue, dof, expected = stats.chi2_contingency(obs)
print(pvalue)

0.001892528960792166

In [9]:
statistics, dof, expected

(np.float64(12.53968253968254),
 2,
 array([[45., 35., 20.],
        [45., 35., 20.]]))

In [10]:
# 기대값 

pd.DataFrame(expected, columns = cross_table.columns, index = cross_table.index)

만족도    만족    보통   불만족
성별
남성   45.0  35.0  20.0
여성   45.0  35.0  20.0